### ISSUE TITLE
Interface PHPWatch\SymbolData\DataSourceInterface should be ignored

### ISSUE THREAD

**Issue by Art4** [PHPWatch/symbol-data-builder#1]
Just noted the PHPWatch\SymbolData\DataSourceInterface in the inferfaces list.

Btw, great project. I'm a fan and user of PHP.watch and would like to ask if I can help you on this project? 😊

**Comment by Ayesh** [comment]
Thank you @Art4 for your kind words, really appreciate it!

I thought to use an interface to make it more cleaner to implement various data sources. For the moment, all data sources extend `DataSourceBase` abstract class, but I don't think it can be used for the new data sources I'm thinking to add. 

I'm thinking to work on a "Function Stub Source" and a "Class Stub Source" sources that, using Reflection API, creates a stub files for all functions and classes, along with their parameters, properties, return values, and attributes. In addition to the stub text itself, a structured data pattern would be helpful too, I think. Didn't really had the time to work on them yet, but I could use any help I can get. I know [phpstan](https://github.com/phpstan/php-8-stubs) is doing this for stubs, so reusing it could make it easier.
Thank you 🙏.

**Comment by Art4** [comment]
In `ClassesListSource.php` you've created a filter for classes starting with `PHPWatch`, `Composer`, etc. Same will be needed for interfaces.

But what do you think about collecting data from `get_declared_classes()`, `get_declared_interfaces()` and so on in `bin/dump.php` right before requiring the `autoload.php`?

phpstan seems to scans the php-src directly. I have to take a close look.

**Comment by Ayesh** [comment]
Sorry I didn't understand what you meant by ignoring at first, but you are right the the interface was leaked to the interfaces list. Fixed now. 

Gathering classes and interfaces before the autoloader should work too, I will keep in mind if it comes to a point that we can't iterate and remove. Thank you.

**Comment by Art4** [comment]
Thanks and sorry for not communicating this clear enough. 😊 

> Gathering classes and interfaces before the autoloader should work too, I will keep in mind if it comes to a point that we can't iterate and remove.

I will open a PR.
