### ISSUE TITLE
Workflow "Symbol updater" is disabled

### ISSUE THREAD

**Issue by Art4** [PHPWatch/symbol-data-builder#7]
> ⚠️ This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs. 

See https://github.com/PHPWatch/symbol-data-builder/actions/workflows/symbol-update.yml

![grafik](https://github.com/PHPWatch/symbol-data-builder/assets/2162994/846b2f8d-b6ad-44fd-93e3-2fd281a5efd5)

**Comment by Ayesh** [comment]
Thank you @Art4. I just enabled it and forced a manual run as well.
